module.exports=[
  // SidebarItem
  {
    text:'源码分析',
    children:[
      {
        text:'Vue',
        children:[
          {
            text:'computed',
            link:'/source-code/vue/computed',
          },
          {
            text:'keep-alive',
            link:'/source-code/vue/keep-alive',
          },
          {
            text:'响应式原理',
            link:'/source-code/vue/reactive',
          },
          {
            text:'Vue3响应式原理',
            link:'/source-code/vue/vue3-reactive',
          }
        ]
      }
    ]
  },
  {
    text:'业务开发总结',
    children:[
      {
        text:'使用rxjs管理枚举数据',
        link:'/business/enums-by-rxjs'
      },
      {
        text:'web端与客户端通信',
        link:'/business/js-bridge'
      },
      {
        text:'vue',
        children:[
          {
            text:'表格列复用',
            link:'/business/vue/table-column'
          },
          {
            text:'函数式弹窗调用',
            link:'/business/vue/functional-invoke-dialog'
          },
          {
            text:'路由懒加载过度动画',
            link:'/business/vue/route-lazy-load-loading'
          }
        ]
      }
    ]
  },
  {
    text:'监控',
    children:[
      {
        text:'错误捕获',
        link:'/monitor/error-catch'
      },
      {
        text:'workbox踩坑记录',
        link:'/monitor/workbox'
      },
      {
        text:'加载性能指标',
        link:'/monitor/performance'
      }
    ]
  },
  {
    text: '基础知识',
    children: [
      {
        text: 'bfc',
        link: '/base/bfc',
      },
      {
        text: 'event-loop',
        link: '/base/event-loop',
      },
      {
        text:'typescript',
        children:[
          {
            text:'process.env变量声明合并',
            link:'/base/ts/process-env'
          },
          {
            text:'infer(todo)',
            link:'/base/ts/infer'
          }
        ]
      }
    ],
  },
 
  {
    text:'组件',
    children:[
      {
        text:'vue',
        children:[
          {
            text:'render',
            link:'/components/vue/render'
          },
          {
            text:'虚拟列表',
            link:'/components/vue/virtual-list'
          }
        ]
      },
      {
        text:'karma单元测试环境搭建(todo)',
        link:'/components/karma-example'
      }
    ]
  },
 
  {
    text:'问题记录',
    children:[
      {
        text:'开发环境搭建相关',
        link:'/issues/dev-env',
      },
      {
        text:'ios web',
        link:'/issues/ios-web',
      },
      {
        text:'npm link调试错处理',
        link:'/issues/npm-link-dev',
      },
      {
        text:'yarn迁移到pnpm',
        link:'/issues/migrate-to-pnpm',
      },
      {
        text:'vite问题记录',
        link:'/issues/vite',
      }
    ]
  },
  
]